server:
  port: 8081
  servlet:
    context-path: /sales

spring:
  application:
    name: sales
  profiles:
    active:
     - "test"

  rabbitmq:
    host: localhost
    port: 5672
    username: nando.systempro@hotmail.com
    password: Fe281244
        
ProdutocontrolStock:
  rabbitmq:
    exchange: ProdutocontrolStock.exchange
    queue: ProdutocontrolStock.ProdutocontrolStock.queue

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl: 
      defaultZone: http://localhost:8761/registry/eureka